/**
 * Knowledge Centre curriculum — original ABC course map.
 * Bodies live in lib/academy/content/*.js
 */

const TRACKS = [
  {
    id: "foundations",
    no: 1,
    title: "Foundations",
    level: "Foundation",
    color: "mint",
    blurb: "How markets work, who is on the other side, and why price is not value.",
    minutes: 95,
  },
  {
    id: "india",
    no: 2,
    title: "Indian Market Architecture",
    level: "Foundation",
    color: "cobalt",
    blurb: "SEBI, NSE, BSE, MCX, demat, T+1 settlement, and how an order is matched.",
    minutes: 110,
  },
  {
    id: "equity",
    no: 3,
    title: "Equity Investing",
    level: "Foundation",
    color: "gold",
    blurb: "Shares, quotes, indices, corporate actions, IPOs, and a process for not buying noise.",
    minutes: 100,
  },
  {
    id: "fundamentals",
    no: 4,
    title: "Fundamental Analysis",
    level: "Intermediate",
    color: "mint",
    blurb: "Statements, cash, ratios, valuation, quarterlies, earnings quality, and a one-page scorecard.",
    minutes: 130,
  },
  {
    id: "technicals",
    no: 5,
    title: "Technical Analysis",
    level: "Intermediate",
    color: "cobalt",
    blurb: "Structure, the full indicator kit (ATR, bands, Supertrend, ADX, Ichimoku, volume), and what charts cannot do.",
    minutes: 120,
  },
  {
    id: "futures",
    no: 6,
    title: "Futures & Leverage",
    level: "Intermediate",
    color: "terracotta",
    blurb: "Contract specs, mark-to-market, margins, basis, hedges, and the F&O ban list.",
    minutes: 115,
  },
  {
    id: "options",
    no: 7,
    title: "Options",
    level: "Advanced",
    color: "cobalt",
    blurb: "Calls, puts, premium, IV, Greeks, spreads, assignment, and sizing an options book.",
    minutes: 140,
  },
  {
    id: "commodities",
    no: 8,
    title: "Commodities & Currency",
    level: "Advanced",
    color: "gold",
    blurb: "MCX metals and energy, agri, USDINR, BeES vs futures, and how to write a commodity strategy card.",
    minutes: 100,
  },
  {
    id: "psychology",
    no: 9,
    title: "Trading Psychology",
    level: "Desk",
    color: "terracotta",
    blurb: "Bias, FOMO, revenge trading, journaling, and rules that survive a bad day.",
    minutes: 110,
  },
  {
    id: "risk",
    no: 10,
    title: "Risk & Money Management",
    level: "Desk",
    color: "mint",
    blurb: "R-multiples, correlation, Kelly, expectancy, heat, and a one-page risk policy.",
    minutes: 115,
  },
  {
    id: "regulations",
    no: 11,
    title: "Regulation, Tax & Operations",
    level: "Desk",
    color: "cobalt",
    blurb: "Insider rules, STT, capital gains, F&O tax, pledge, SCORES, and NISM map.",
    minutes: 105,
  },
  {
    id: "desk",
    no: 12,
    title: "The Professional Desk",
    level: "Desk",
    color: "gold",
    blurb: "Playbooks, honest backtests, execution, flows, events, and a 90-day apprenticeship.",
    minutes: 120,
  },
  {
    id: "library",
    no: 13,
    title: "Library & Field Kit",
    level: "All levels",
    color: "mint",
    blurb: "Official classrooms, books to buy legally, worksheets, glossary — no pirated files.",
    minutes: 40,
  },
  {
    id: "strategies",
    no: 14,
    title: "Option Strategies",
    level: "Advanced",
    color: "terracotta",
    blurb: "Turn a market view into a defined structure: spreads, condors, calendars, and when not to adjust.",
    minutes: 180,
  },
  {
    id: "funds",
    no: 15,
    title: "Mutual Funds & ETFs",
    level: "Foundation",
    color: "mint",
    blurb: "NAV, TER, SIP, Nifty BeES and other ETFs, premium/discount, and how funds are taxed in India.",
    minutes: 140,
  },
  {
    id: "bonds",
    no: 16,
    title: "Bonds & Government Securities",
    level: "Intermediate",
    color: "gold",
    blurb: "Yield, duration, G-Secs, T-bills, SDLs, credit risk, and why bond prices move when rates move.",
    minutes: 120,
  },
  {
    id: "sectors",
    no: 17,
    title: "Sector Analysis",
    level: "Intermediate",
    color: "cobalt",
    blurb: "How banks, IT, energy, auto, pharma and consumer businesses actually make money in India.",
    minutes: 130,
  },
  {
    id: "modelling",
    no: 18,
    title: "Financial Modelling",
    level: "Advanced",
    color: "mint",
    blurb: "Link three statements, build revenue and working capital, run a DCF, and stress the assumptions.",
    minutes: 140,
  },
  {
    id: "insurance",
    no: 19,
    title: "Insurance",
    level: "Foundation",
    color: "gold",
    blurb: "Term, health, and why a ULIP is not a substitute for either investing or covering risk.",
    minutes: 80,
  },
  {
    id: "nps",
    no: 20,
    title: "NPS & Retirement",
    level: "Foundation",
    color: "cobalt",
    blurb: "National Pension System: tiers, asset classes, tax, annuity, and how it sits next to EPF and PPF.",
    minutes: 80,
  },
  {
    id: "sse",
    no: 21,
    title: "Social Stock Exchange",
    level: "Foundation",
    color: "mint",
    blurb: "How SSE lets non-profits and social enterprises raise funds, and what a retail investor should know.",
    minutes: 45,
  },
  {
    id: "positioning",
    no: 22,
    title: "OI, Greeks & Positioning",
    level: "Advanced",
    color: "terracotta",
    blurb: "Open interest, strike walls, max pain, dealer gamma, theta, vanna and a daily Nifty positioning checklist.",
    minutes: 180,
  },
  {
    id: "ai",
    no: 23,
    title: "AI in Trading",
    level: "Desk",
    color: "cobalt",
    blurb: "How AI can make research easier — copilot not autopilot, data leakage, walk-forward, and a human gate.",
    minutes: 90,
  },
  {
    id: "microstructure",
    no: 24,
    title: "Market Microstructure",
    level: "Advanced",
    color: "terracotta",
    blurb: "The book, auctions, impact, tick size, blocks, rebalances, borrow — how prints are actually made in India.",
    minutes: 160,
  },
  {
    id: "volatility",
    no: 25,
    title: "Volatility Desk",
    level: "Advanced",
    color: "cobalt",
    blurb: "IV versus realised, skew, selling and buying vol, calendars, delta-hedge, dispersion, and a one-page vol dashboard.",
    minutes: 170,
  },
  {
    id: "specials",
    no: 26,
    title: "Special Situations",
    level: "Advanced",
    color: "gold",
    blurb: "Earnings, buybacks, demergers, open offers, QIPs, delisting, rights — trades with a document and a date.",
    minutes: 160,
  },
  {
    id: "macro",
    no: 27,
    title: "Macro for Indian Books",
    level: "Intermediate",
    color: "mint",
    blurb: "RBI, USDINR, crude, FII, Budget, monsoon, the Fed gap, liquidity — a six-cell overnight note.",
    minutes: 150,
  },
  {
    id: "portfolio",
    no: 28,
    title: "Portfolio Construction",
    level: "Intermediate",
    color: "gold",
    blurb: "Household versus trading book, factors, rebalance, overlays, barbell, IPS, and a quarterly report to yourself.",
    minutes: 150,
  },
  {
    id: "alts",
    no: 29,
    title: "REITs, InvITs & Other Sleeves",
    level: "Intermediate",
    color: "cobalt",
    blurb: "REITs, InvITs, SGBs, GIFT City, global feeders, PMS/AIF — and a proxy test before you pay a wrapper.",
    minutes: 110,
  },
  {
    id: "systems",
    no: 30,
    title: "Systematic Trading",
    level: "Desk",
    color: "terracotta",
    blurb: "Rules, regimes, robustness, live versus backtest, a pipeline, and when to retire a system.",
    minutes: 150,
  },
  {
    id: "hedging",
    no: 31,
    title: "Hedging a Book",
    level: "Advanced",
    color: "mint",
    blurb: "Named risk, futures overlays, collars, FX/commodity hedges, event and tail insurance, a hedge register.",
    minutes: 130,
  },
  {
    id: "indices",
    no: 32,
    title: "Index Mechanics",
    level: "Advanced",
    color: "cobalt",
    blurb: "Nifty as a recipe, Bank Nifty tails, India VIX, breadth, equal-weight, and an 8-minute open card.",
    minutes: 150,
  },
  {
    id: "intraday",
    no: 33,
    title: "Intraday Playbooks",
    level: "Advanced",
    color: "terracotta",
    blurb: "Named day jobs: opening range, VWAP, gaps, expiry Thursday, news clocks, and a kill switch.",
    minutes: 150,
  },
  {
    id: "relval",
    no: 34,
    title: "Relative Value",
    level: "Desk",
    color: "gold",
    blurb: "Spreads not stories: cash-future basis, BN vs Nifty, pairs, calendars, BeES residual — leftover beta named.",
    minutes: 155,
  },
  {
    id: "rates",
    no: 35,
    title: "Rates Desk",
    level: "Advanced",
    color: "mint",
    blurb: "RBI corridor, OMO/VRR, G-sec curve, Bank Nifty as a rates animal, credit spreads, a four-minute dashboard.",
    minutes: 150,
  },
  {
    id: "fx",
    no: 36,
    title: "FX Desk (USDINR)",
    level: "Advanced",
    color: "cobalt",
    blurb: "Policy pair, importer vs spec, oil-FII-dollar bosses, intervention, crosses, a hedge register.",
    minutes: 145,
  },
  {
    id: "forensic",
    no: 37,
    title: "Forensic & Governance",
    level: "Advanced",
    color: "terracotta",
    blurb: "Cash vs profit, related parties, auditors, pledge fuses, SEBI orders, a two-red walk-away rule.",
    minutes: 155,
  },
  {
    id: "tradertax",
    no: 38,
    title: "Trader Tax & Books",
    level: "Desk",
    color: "gold",
    blurb: "F&O as business income, turnover, ITR-3, STT 0.15% from Apr 2026, monthly close, a March desk.",
    minutes: 145,
  },
  {
    id: "intermarket",
    no: 39,
    title: "Intermarket India",
    level: "Intermediate",
    color: "mint",
    blurb: "Four screens: Nifty, USDINR, crude, US futures — oil-rupee triangle, crash correlation, when the map lies.",
    minutes: 145,
  },
  {
    id: "researchcraft",
    no: 40,
    title: "Research Craft",
    level: "Desk",
    color: "cobalt",
    blurb: "Thesis plus kill, evidence hierarchy, one-page notes, WIP limits, ethics, writing for a tired you.",
    minutes: 145,
  },
];

const LESSONS = [
  // Foundations
  ["foundations", "foundations-01", "How a market actually works", 12, ["article", "diagram", "quiz"]],
  ["foundations", "foundations-02", "Price, value and expected return", 12, ["article", "formula", "quiz"]],
  ["foundations", "foundations-03", "Risk is not just volatility", 12, ["article", "diagram", "quiz"]],
  ["foundations", "foundations-04", "Compounding and the long game", 10, ["article", "formula", "worksheet"]],
  ["foundations", "foundations-05", "Who is on the other side of your trade", 12, ["article", "quiz"]],
  ["foundations", "foundations-06", "Orders, liquidity and the bid–ask spread", 14, ["article", "diagram", "quiz"]],
  ["foundations", "foundations-07", "Investing, trading and hedging", 10, ["article", "quiz"]],
  ["foundations", "foundations-08", "Build your personal market map", 12, ["article", "worksheet"]],
  // India
  ["india", "india-01", "SEBI, exchanges and the Indian rulebook", 14, ["article", "source"]],
  ["india", "india-02", "Demat, trading account and KYC", 12, ["article", "quiz"]],
  ["india", "india-03", "Cash session hours and T+1 settlement", 12, ["article", "diagram"]],
  ["india", "india-04", "Indices: Nifty, Bank Nifty, Sensex", 12, ["article", "quiz"]],
  ["india", "india-05", "Circuit filters, ASM and GSM", 12, ["article", "caution"]],
  ["india", "india-06", "Corporate actions that change your position", 14, ["article", "table"]],
  ["india", "india-07", "Brokers, depositories and the fee stack", 12, ["article", "worksheet"]],
  ["india", "india-08", "From click to matching engine", 14, ["article", "diagram"]],
  // Equity
  ["equity", "equity-01", "What a share legally is", 10, ["article", "quiz"]],
  ["equity", "equity-02", "How to read an Indian stock quote", 12, ["article", "diagram"]],
  ["equity", "equity-03", "Market cap, free float and liquidity", 12, ["article", "formula"]],
  ["equity", "equity-04", "Dividends, bonus, splits and rights", 12, ["article", "table"]],
  ["equity", "equity-05", "Sectors, cycles and business models", 12, ["article"]],
  ["equity", "equity-06", "IPOs without the brochure language", 14, ["article", "caution"]],
  ["equity", "equity-07", "A process for building a watchlist", 12, ["article", "worksheet"]],
  ["equity", "equity-08", "When the correct action is not to buy", 10, ["article", "quiz"]],
  // Fundamentals
  ["fundamentals", "fundamentals-01", "The three financial statements", 16, ["article", "diagram"]],
  ["fundamentals", "fundamentals-02", "Revenue quality, margins and cash", 14, ["article", "formula"]],
  ["fundamentals", "fundamentals-03", "Balance-sheet quality and leverage", 14, ["article", "caution"]],
  ["fundamentals", "fundamentals-04", "Ratios that earn their keep", 14, ["article", "table"]],
  ["fundamentals", "fundamentals-05", "Valuation: multiples versus intrinsic", 16, ["article", "formula"]],
  ["fundamentals", "fundamentals-06", "Moats and capital allocation", 14, ["article"]],
  ["fundamentals", "fundamentals-07", "Red flags and forensic basics", 14, ["article", "caution"]],
  ["fundamentals", "fundamentals-08", "Reading an annual report in 90 minutes", 16, ["article", "worksheet"]],
  ["fundamentals", "fundamentals-09", "Working capital and the cash cycle", 14, ["article", "formula"]],
  ["fundamentals", "fundamentals-10", "A DCF you can actually defend", 16, ["article", "formula"]],
  ["fundamentals", "fundamentals-11", "Peer comparison without fooling yourself", 12, ["article", "table"]],
  ["fundamentals", "fundamentals-12", "Promoters, pledges and related parties", 14, ["article", "caution"]],
  ["fundamentals", "fundamentals-13", "DuPont: why ROE actually moved", 14, ["article", "formula", "quiz"]],
  ["fundamentals", "fundamentals-14", "Free cash flow versus reported profit", 14, ["article", "formula", "quiz"]],
  ["fundamentals", "fundamentals-15", "Quarterly results and the concall", 16, ["article", "worksheet", "quiz"]],
  ["fundamentals", "fundamentals-16", "Earnings quality and accruals", 14, ["article", "table", "quiz"]],
  ["fundamentals", "fundamentals-17", "Capital allocation: dividends, buybacks, M&A", 14, ["article", "quiz"]],
  ["fundamentals", "fundamentals-18", "A one-page fundamental scorecard", 14, ["article", "worksheet", "quiz"]],
  // Technicals
  ["technicals", "technicals-01", "Charts are a language, not a forecast", 12, ["article", "caution"]],
  ["technicals", "technicals-02", "Candlesticks and market structure", 14, ["article", "diagram"]],
  ["technicals", "technicals-03", "Trend, range, support and resistance", 14, ["article", "diagram"]],
  ["technicals", "technicals-04", "Volume and participation", 12, ["article"]],
  ["technicals", "technicals-05", "Moving averages and VWAP", 14, ["article", "formula"]],
  ["technicals", "technicals-06", "RSI and MACD — what they measure", 14, ["article"]],
  ["technicals", "technicals-07", "Patterns and honest probabilities", 12, ["article", "caution"]],
  ["technicals", "technicals-08", "A technical checklist you can audit", 12, ["article", "worksheet"]],
  ["technicals", "technicals-09", "Gaps, news days and opening range", 12, ["article"]],
  ["technicals", "technicals-10", "Multiple timeframes without confusion", 12, ["article"]],
  ["technicals", "technicals-11", "Market breadth and internals", 12, ["article"]],
  ["technicals", "technicals-12", "Turning charts into a written playbook", 12, ["article", "worksheet"]],
  ["technicals", "technicals-13", "ATR: a ruler for stops and size", 14, ["article", "formula", "quiz"]],
  ["technicals", "technicals-14", "Bollinger, Keltner and the squeeze", 14, ["article", "diagram", "quiz"]],
  ["technicals", "technicals-15", "Supertrend, Donchian and channel systems", 14, ["article", "diagram", "quiz"]],
  ["technicals", "technicals-16", "ADX and directional movement", 14, ["article", "table", "quiz"]],
  ["technicals", "technicals-17", "Stochastic, CCI and the oscillator family", 14, ["article", "formula", "quiz"]],
  ["technicals", "technicals-18", "Ichimoku without the mysticism", 14, ["article", "diagram", "quiz"]],
  ["technicals", "technicals-19", "Fibonacci, pivots and measured moves", 12, ["article", "quiz"]],
  ["technicals", "technicals-20", "Volume tools and India delivery %", 14, ["article", "quiz"]],
  ["technicals", "technicals-21", "Divergence, failure swings and indicator lies", 14, ["article", "quiz"]],
  ["technicals", "technicals-22", "Build an indicator stack that does not fight itself", 14, ["article", "worksheet", "quiz"]],
  // Futures
  ["futures", "futures-01", "Why derivatives exist", 12, ["article"]],
  ["futures", "futures-02", "Futures specs, lots and tick value", 14, ["article", "table"]],
  ["futures", "futures-03", "Mark-to-market and margins", 14, ["article", "formula"]],
  ["futures", "futures-04", "Basis, roll and expiry week", 14, ["article"]],
  ["futures", "futures-05", "Index futures versus stock futures", 12, ["article"]],
  ["futures", "futures-06", "Hedging a cash portfolio with futures", 14, ["article", "formula"]],
  ["futures", "futures-07", "Leverage: the silent account killer", 12, ["article", "caution"]],
  ["futures", "futures-08", "Ban list, MWPL and position limits", 12, ["article", "source"]],
  // Options
  ["options", "options-01", "Call and put in plain language", 14, ["article", "diagram"]],
  ["options", "options-02", "Payoff diagrams you can draw by hand", 14, ["article", "diagram"]],
  ["options", "options-03", "Premium, moneyness and time decay", 14, ["article", "formula"]],
  ["options", "options-04", "Implied volatility and the smile", 16, ["article"]],
  ["options", "options-05", "Greeks: delta through vega", 16, ["article", "table"]],
  ["options", "options-06", "Spreads, condors and butterflies", 16, ["article", "diagram"]],
  ["options", "options-07", "Exercise, assignment and settlement", 12, ["article"]],
  ["options", "options-08", "Sizing an options book", 14, ["article", "worksheet"]],
  ["options", "options-09", "How to read an option chain", 14, ["article", "table"]],
  ["options", "options-10", "Weekly versus monthly options", 12, ["article"]],
  ["options", "options-11", "Put-call parity in plain language", 14, ["article", "formula"]],
  ["options", "options-12", "Trading volatility, not just direction", 14, ["article"]],
  // Commodities
  ["commodities", "commodities-01", "Why commodities are a different animal", 12, ["article"]],
  ["commodities", "commodities-02", "MCX gold, silver, crude and gas", 14, ["article", "table"]],
  ["commodities", "commodities-03", "Agri contracts and seasonality", 12, ["article"]],
  ["commodities", "commodities-04", "USDINR and currency futures", 12, ["article"]],
  ["commodities", "commodities-05", "Hedgers, inventory and the roll", 12, ["article"]],
  ["commodities", "commodities-06", "Commodity risk versus equity risk", 12, ["article"]],
  ["commodities", "commodities-07", "Margins, delivery and intent", 12, ["article", "caution"]],
  ["commodities", "commodities-08", "A commodity research notebook", 10, ["article", "worksheet"]],
  ["commodities", "commodities-09", "Gold: MCX, COMEX and Gold BeES", 14, ["article", "quiz"]],
  ["commodities", "commodities-10", "Silver: the jumpy cousin", 12, ["article", "quiz"]],
  ["commodities", "commodities-11", "Crude and natural gas", 14, ["article", "caution", "quiz"]],
  ["commodities", "commodities-12", "Copper and industrial metals", 12, ["article", "quiz"]],
  ["commodities", "commodities-13", "Spreads and the gold–silver ratio", 14, ["article", "quiz"]],
  ["commodities", "commodities-14", "Write a commodity strategy card", 14, ["article", "worksheet", "quiz"]],
  // Psychology
  ["psychology", "psychology-01", "The account is a mirror", 12, ["article"]],
  ["psychology", "psychology-02", "A working catalogue of biases", 14, ["article", "table"]],
  ["psychology", "psychology-03", "Process versus outcome", 12, ["article"]],
  ["psychology", "psychology-04", "Drawdown: math and mood", 12, ["article"]],
  ["psychology", "psychology-05", "Revenge trading and overtrading", 12, ["article", "caution"]],
  ["psychology", "psychology-06", "A journal that changes behaviour", 14, ["article", "worksheet"]],
  ["psychology", "psychology-07", "Sleep, routine and decision fatigue", 10, ["article"]],
  ["psychology", "psychology-08", "Rules that survive a bad Thursday", 12, ["article", "quiz"]],
  // Risk
  ["risk", "risk-01", "Define risk before you hunt edge", 12, ["article"]],
  ["risk", "risk-02", "Position sizing from R", 14, ["article", "formula", "worksheet"]],
  ["risk", "risk-03", "Correlation and hidden concentration", 12, ["article"]],
  ["risk", "risk-04", "Stops: price, time and thesis", 12, ["article"]],
  ["risk", "risk-05", "Kelly, half-Kelly and ruin", 14, ["article", "formula"]],
  ["risk", "risk-06", "Expectancy and sample size", 12, ["article", "formula"]],
  ["risk", "risk-07", "Portfolio heat and daily loss caps", 12, ["article"]],
  ["risk", "risk-08", "Write a one-page risk policy", 12, ["article", "worksheet"]],
  // Regulations
  ["regulations", "regulations-01", "Insider trading and market abuse", 14, ["article", "source"]],
  ["regulations", "regulations-02", "STT, stamp duty and brokerage GST", 12, ["article", "table"]],
  ["regulations", "regulations-03", "Equity taxation in India", 14, ["article"]],
  ["regulations", "regulations-04", "How F&O profits are taxed", 14, ["article", "caution"]],
  ["regulations", "regulations-05", "Pledge, MTF and funding risk", 12, ["article", "caution"]],
  ["regulations", "regulations-06", "Disclosures you are required to read", 12, ["article", "source"]],
  ["regulations", "regulations-07", "SCORES and investor grievance", 10, ["article", "source"]],
  ["regulations", "regulations-08", "NISM map: which exam for which seat", 12, ["article", "table"]],
  // Desk
  ["desk", "desk-01", "Write a playbook, not a wish", 12, ["article", "worksheet"]],
  ["desk", "desk-02", "Backtests that do not lie", 14, ["article", "caution"]],
  ["desk", "desk-03", "Execution, slippage and impact", 12, ["article"]],
  ["desk", "desk-04", "Reading FII/DII and options open interest", 14, ["article"]],
  ["desk", "desk-05", "Event risk: RBI, Budget, results", 12, ["article"]],
  ["desk", "desk-06", "A multi-timeframe desk workflow", 12, ["article"]],
  ["desk", "desk-07", "Costs, break-even and the professional P&L", 12, ["article", "formula"]],
  ["desk", "desk-08", "A 90-day apprenticeship plan", 14, ["article", "worksheet"]],
  // Library
  ["library", "library-01", "Official classrooms: NSE, SEBI, NISM, MCX", 10, ["source", "article"]],
  ["library", "library-02", "Books to buy legally — not pirate", 12, ["article"]],
  ["library", "library-03", "Worksheets: journal, sizing, risk policy", 10, ["worksheet"]],
  ["library", "library-04", "Field glossary: 80 terms you will actually use", 16, ["article"]],
  ["strategies", "strategies-01", "From a view to a structure", 12, ["article"]],
  ["strategies", "strategies-02", "Bull call and bear put spreads", 14, ["article", "example"]],
  ["strategies", "strategies-03", "Credit spreads: selling defined risk", 14, ["article", "example"]],
  ["strategies", "strategies-04", "Covered calls and cash-secured puts", 14, ["article"]],
  ["strategies", "strategies-05", "Straddles and strangles", 14, ["article", "lab"]],
  ["strategies", "strategies-06", "Iron condor, step by step", 16, ["article", "example"]],
  ["strategies", "strategies-07", "Butterflies and iron flies", 14, ["article"]],
  ["strategies", "strategies-08", "Calendars and diagonals", 14, ["article"]],
  ["strategies", "strategies-09", "Ratio spreads and why they bite", 12, ["article", "caution"]],
  ["strategies", "strategies-10", "Adjustments: when to stand down", 12, ["article"]],
  ["strategies", "strategies-11", "Match the strategy to the view", 14, ["article", "table"]],
  ["strategies", "strategies-12", "Write a one-page strategy card", 12, ["article", "worksheet"]],
  ["funds", "funds-01", "What a mutual fund actually is", 12, ["article"]],
  ["funds", "funds-02", "NAV, AUM and the expense ratio", 12, ["article", "formula"]],
  ["funds", "funds-03", "Equity, debt and hybrid funds", 12, ["article", "table"]],
  ["funds", "funds-04", "Index funds and ETFs", 14, ["article"]],
  ["funds", "funds-05", "SIP, STP and SWP", 12, ["article"]],
  ["funds", "funds-06", "Direct versus regular plans", 10, ["article"]],
  ["funds", "funds-07", "How to read a fund factsheet", 14, ["article", "worksheet"]],
  ["funds", "funds-08", "Riskometer and suitability", 10, ["article"]],
  ["funds", "funds-09", "How mutual funds are taxed", 14, ["article"]],
  ["funds", "funds-10", "A simple allocation you can live with", 12, ["article", "worksheet"]],
  ["funds", "funds-11", "Nifty BeES: an ETF, not a mysterious fund", 14, ["article", "quiz"]],
  ["funds", "funds-12", "ETF premium, discount and iNAV", 14, ["article", "formula", "quiz"]],
  ["funds", "funds-13", "Index fund vs ETF vs Nifty futures", 14, ["article", "table", "quiz"]],
  ["funds", "funds-14", "Gold BeES vs futures vs jewellery", 12, ["article", "quiz"]],
  ["bonds", "bonds-01", "What a bond promises to pay", 12, ["article"]],
  ["bonds", "bonds-02", "Price, yield and duration", 14, ["article", "formula"]],
  ["bonds", "bonds-03", "G-Secs and how India borrows", 12, ["article"]],
  ["bonds", "bonds-04", "T-bills, SDLs and corporate bonds", 12, ["article", "table"]],
  ["bonds", "bonds-05", "Credit risk and ratings", 12, ["article", "caution"]],
  ["bonds", "bonds-06", "What happens when RBI changes rates", 12, ["article"]],
  ["bonds", "bonds-07", "Debt funds versus holding bonds directly", 12, ["article"]],
  ["bonds", "bonds-08", "Building a rupee income ladder", 12, ["article", "worksheet"]],
  ["sectors", "sectors-01", "Why sector context comes first", 10, ["article"]],
  ["sectors", "sectors-02", "Banks and NBFCs", 14, ["article"]],
  ["sectors", "sectors-03", "IT services and global spending", 12, ["article"]],
  ["sectors", "sectors-04", "Energy, oil and metals", 12, ["article"]],
  ["sectors", "sectors-05", "Automobiles and ancillaries", 12, ["article"]],
  ["sectors", "sectors-06", "Pharma and healthcare", 12, ["article"]],
  ["sectors", "sectors-07", "Consumer, staples and discretionary", 12, ["article"]],
  ["sectors", "sectors-08", "Keep a sector notebook", 10, ["article", "worksheet"]],
  ["modelling", "modelling-01", "What a model is for — and not for", 12, ["article"]],
  ["modelling", "modelling-02", "Linking the three statements", 14, ["article", "diagram"]],
  ["modelling", "modelling-03", "Building a revenue forecast", 14, ["article"]],
  ["modelling", "modelling-04", "Working capital in the model", 12, ["article", "formula"]],
  ["modelling", "modelling-05", "Debt, interest and the cash sweep", 12, ["article"]],
  ["modelling", "modelling-06", "Discounted cash flow, piece by piece", 16, ["article", "formula"]],
  ["modelling", "modelling-07", "Scenarios and sensitivity tables", 12, ["article", "table"]],
  ["modelling", "modelling-08", "Model hygiene so you do not fool yourself", 12, ["article", "worksheet"]],
  ["insurance", "insurance-01", "Insurance buys a loss you cannot bear", 10, ["article"]],
  ["insurance", "insurance-02", "Term cover versus bundled products", 12, ["article", "table"]],
  ["insurance", "insurance-03", "Health insurance that actually pays", 12, ["article"]],
  ["insurance", "insurance-04", "How to read a policy document", 12, ["article"]],
  ["insurance", "insurance-05", "Claims: paperwork before the hospital", 10, ["article"]],
  ["insurance", "insurance-06", "How much cover is enough", 12, ["article", "worksheet"]],
  ["nps", "nps-01", "What the National Pension System is", 12, ["article"]],
  ["nps", "nps-02", "Tiers, asset classes and fund managers", 12, ["article", "table"]],
  ["nps", "nps-03", "Active choice versus auto choice", 10, ["article"]],
  ["nps", "nps-04", "Tax treatment of NPS", 12, ["article"]],
  ["nps", "nps-05", "Exit, lump sum and annuity", 12, ["article"]],
  ["nps", "nps-06", "NPS next to EPF, PPF and SIPs", 12, ["article"]],
  ["sse", "sse-01", "What the Social Stock Exchange is", 10, ["article"]],
  ["sse", "sse-02", "Instruments: grants, ZCZP and equity", 12, ["article"]],
  ["sse", "sse-03", "Who can list and who can invest", 10, ["article"]],
  ["sse", "sse-04", "How to think about social returns", 10, ["article"]],
  ["positioning", "positioning-01", "Open interest is a stock, not a story", 16, ["article", "diagram", "quiz"]],
  ["positioning", "positioning-02", "Price plus change in OI: four quadrants", 16, ["article", "diagram", "table", "quiz"]],
  ["positioning", "positioning-03", "Put-call ratio: temperature, not timing", 14, ["article", "formula", "quiz"]],
  ["positioning", "positioning-04", "Strike-wise OI: walls, magnets and fuel", 16, ["article", "diagram", "quiz"]],
  ["positioning", "positioning-05", "Max pain, pin risk and expiry week", 16, ["article", "formula", "quiz"]],
  ["positioning", "positioning-06", "Volume vs OI vs IV: three cameras", 14, ["article", "table", "quiz"]],
  ["positioning", "positioning-07", "Delta as a position you already have", 16, ["article", "formula", "quiz"]],
  ["positioning", "positioning-08", "Gamma: how a book mutates with spot", 16, ["article", "diagram", "quiz"]],
  ["positioning", "positioning-09", "Dealer gamma, GEX and the flip", 16, ["article", "diagram", "quiz"]],
  ["positioning", "positioning-10", "Theta: rent, weekends and expiry decay", 16, ["article", "diagram", "quiz"]],
  ["positioning", "positioning-11", "Vega, vanna, charm — the second-order desk", 16, ["article", "table", "quiz"]],
  ["positioning", "positioning-12", "A daily OI and Greeks research checklist", 16, ["article", "worksheet", "quiz"]],
  ["ai", "ai-01", "What AI can and cannot do on a desk", 16, ["article", "diagram", "quiz"]],
  ["ai", "ai-02", "Data, features and leakage", 14, ["article", "caution", "quiz"]],
  ["ai", "ai-03", "Models worth starting with", 14, ["article", "quiz"]],
  ["ai", "ai-04", "Overfitting, walk-forward and costs", 16, ["article", "formula", "quiz"]],
  ["ai", "ai-05", "AI as copilot — research, not autopilot", 16, ["article", "worksheet", "quiz"]],
  ["ai", "ai-06", "A responsible AI trading workflow", 14, ["article", "caution", "quiz"]],
  ["microstructure", "microstructure-01", "Price is a print, the book is the paragraph", 16, ["article", "table", "quiz"]],
  ["microstructure", "microstructure-02", "The 9:08 call auction is a draft", 16, ["article", "caution", "quiz"]],
  ["microstructure", "microstructure-03", "The close is a different market", 14, ["article", "table", "quiz"]],
  ["microstructure", "microstructure-04", "Impact, shortfall and slicing size", 16, ["article", "formula", "quiz"]],
  ["microstructure", "microstructure-05", "Tick size, bands, ASM and the ban list", 14, ["article", "quiz"]],
  ["microstructure", "microstructure-06", "Block and bulk deals without copying them", 14, ["article", "quiz"]],
  ["microstructure", "microstructure-07", "Index additions are a calendar, not a gift", 16, ["article", "quiz"]],
  ["microstructure", "microstructure-08", "Corporate-action adjustments on F&O", 14, ["article", "caution", "quiz"]],
  ["microstructure", "microstructure-09", "Borrow, shorts and STBT reality in India", 14, ["article", "quiz"]],
  ["microstructure", "microstructure-10", "Write an execution clause on every ticket", 14, ["article", "worksheet", "quiz"]],
  ["volatility", "volatility-01", "IV is rent, realised is the receipt", 16, ["article", "formula", "quiz"]],
  ["volatility", "volatility-02", "Smile, skew and the surface", 16, ["article", "table", "quiz"]],
  ["volatility", "volatility-03", "Selling volatility is selling a jump", 16, ["article", "caution", "quiz"]],
  ["volatility", "volatility-04", "Buying volatility and the implied move", 14, ["article", "formula", "quiz"]],
  ["volatility", "volatility-05", "Calendars: trading the term structure", 16, ["article", "quiz"]],
  ["volatility", "volatility-06", "Delta-hedging as a vol job", 16, ["article", "quiz"]],
  ["volatility", "volatility-07", "Weekends, holidays and Friday afternoon", 14, ["article", "quiz"]],
  ["volatility", "volatility-08", "Index vol versus name vol (dispersion)", 14, ["article", "quiz"]],
  ["volatility", "volatility-09", "A one-page vol dashboard", 14, ["article", "table", "quiz"]],
  ["volatility", "volatility-10", "Vol ethics: the 19th Thursday", 14, ["article", "caution", "quiz"]],
  ["specials", "specials-01", "A special is a document plus a date", 14, ["article", "quiz"]],
  ["specials", "specials-02", "Earnings: implied move versus the print", 16, ["article", "quiz"]],
  ["specials", "specials-03", "Buybacks: tender, proration, leftover long", 16, ["article", "quiz"]],
  ["specials", "specials-04", "Demergers and stub value", 14, ["article", "quiz"]],
  ["specials", "specials-05", "Open offers and deal-break risk", 14, ["article", "quiz"]],
  ["specials", "specials-06", "QIP, OFS and lock-in calendars", 14, ["article", "quiz"]],
  ["specials", "specials-07", "Delisting and reverse book-builds", 14, ["article", "caution", "quiz"]],
  ["specials", "specials-08", "Rights issues are options you already own", 14, ["article", "formula", "quiz"]],
  ["specials", "specials-09", "How index ETFs digest specials", 12, ["article", "quiz"]],
  ["specials", "specials-10", "A specials card: leftover plan included", 14, ["article", "worksheet", "quiz"]],
  ["macro", "macro-01", "Nifty sits in a world of dollars and oil", 16, ["article", "table", "quiz"]],
  ["macro", "macro-02", "RBI: the integer and the words", 16, ["article", "quiz"]],
  ["macro", "macro-03", "USDINR as India's exhaust pipe", 14, ["article", "quiz"]],
  ["macro", "macro-04", "Crude: split the energy complex", 14, ["article", "quiz"]],
  ["macro", "macro-05", "FII/DII as regimes, not oracles", 14, ["article", "quiz"]],
  ["macro", "macro-06", "Union Budget as a vol and sector event", 14, ["article", "quiz"]],
  ["macro", "macro-07", "Monsoon, food CPI and the RBI path", 12, ["article", "quiz"]],
  ["macro", "macro-08", "The Fed trades you overnight", 14, ["article", "quiz"]],
  ["macro", "macro-09", "Rupee liquidity is a rate, not a vibe", 12, ["article", "quiz"]],
  ["macro", "macro-10", "A six-cell overnight note", 14, ["article", "table", "quiz"]],
  ["portfolio", "portfolio-01", "Household book versus trading book", 16, ["article", "caution", "quiz"]],
  ["portfolio", "portfolio-02", "Factors: momentum, quality, value, low-vol", 16, ["article", "table", "quiz"]],
  ["portfolio", "portfolio-03", "Rebalancing bands, not moods", 14, ["article", "quiz"]],
  ["portfolio", "portfolio-04", "Tax-aware clicks (not loophole theatre)", 12, ["article", "quiz"]],
  ["portfolio", "portfolio-05", "Overlays: gold, global, duration", 14, ["article", "quiz"]],
  ["portfolio", "portfolio-06", "The barbell and watchability", 12, ["article", "quiz"]],
  ["portfolio", "portfolio-07", "Portfolio drawdown budgets", 14, ["article", "quiz"]],
  ["portfolio", "portfolio-08", "A liquidity ladder for rupee liabilities", 14, ["article", "quiz"]],
  ["portfolio", "portfolio-09", "One-page IPS, especially the forbidden list", 14, ["article", "worksheet", "quiz"]],
  ["portfolio", "portfolio-10", "A quarterly report to yourself", 12, ["article", "quiz"]],
  ["alts", "alts-01", "REITs are not fixed deposits", 14, ["article", "quiz"]],
  ["alts", "alts-02", "InvITs: annuity versus traffic risk", 14, ["article", "quiz"]],
  ["alts", "alts-03", "Sovereign Gold Bonds versus BeES versus jewellery", 14, ["article", "quiz"]],
  ["alts", "alts-04", "GIFT City / IFSC is a different perimeter", 12, ["article", "quiz"]],
  ["alts", "alts-05", "Global equities from India: LRS, feeders, FX", 14, ["article", "quiz"]],
  ["alts", "alts-06", "PMS, AIF and paying for access not theatre", 14, ["article", "caution", "quiz"]],
  ["alts", "alts-07", "Commodities as a sleeve, not a personality", 12, ["article", "quiz"]],
  ["alts", "alts-08", "The proxy test before any wrapper", 12, ["article", "quiz"]],
  ["systems", "systems-01", "A system is a rule a tired you can fire", 14, ["article", "quiz"]],
  ["systems", "systems-02", "Regime first, then the child strategy", 16, ["article", "table", "quiz"]],
  ["systems", "systems-03", "Robustness: 20 DMA versus 21", 16, ["article", "caution", "quiz"]],
  ["systems", "systems-04", "Live versus backtest: you are the first slippage", 14, ["article", "quiz"]],
  ["systems", "systems-05", "Sizing inside systems: no feel-multipliers", 14, ["article", "formula", "quiz"]],
  ["systems", "systems-06", "A portfolio of systems and the crash correlator", 14, ["article", "quiz"]],
  ["systems", "systems-07", "Missed signals are missed — don't chase", 12, ["article", "quiz"]],
  ["systems", "systems-08", "Idea → paper → tiny live → scale", 14, ["article", "quiz"]],
  ["systems", "systems-09", "When to retire a system (STT, expiry, you)", 14, ["article", "quiz"]],
  ["systems", "systems-10", "The systems desk: restraint is the craft", 12, ["article", "quiz"]],
  ["hedging", "hedging-01", "Name the risk, then compute the ratio", 16, ["article", "formula", "quiz"]],
  ["hedging", "hedging-02", "Futures overlays and the MTM that 'hurts'", 14, ["article", "quiz"]],
  ["hedging", "hedging-03", "Protective puts and collars as a TER", 16, ["article", "quiz"]],
  ["hedging", "hedging-04", "Importer/exporter hedges versus specs", 14, ["article", "quiz"]],
  ["hedging", "hedging-05", "Event hedges that die when the event dies", 12, ["article", "quiz"]],
  ["hedging", "hedging-06", "Overnight gap: size, puts, or flat", 14, ["article", "quiz"]],
  ["hedging", "hedging-07", "Tail hedges should usually expire worthless", 14, ["article", "quiz"]],
  ["hedging", "hedging-08", "A hedge register so you don't lift winners", 14, ["article", "worksheet", "quiz"]],
  ["options", "options-13", "Conversions, reversals and accidental beta", 14, ["article", "formula", "quiz"]],
  ["options", "options-14", "Thursday: pick a pin role or be flat", 14, ["article", "quiz"]],
  ["options", "options-15", "Broken wings and nicknames that aren't bounds", 12, ["article", "quiz"]],
  ["options", "options-16", "Poor man's covered call, Indian liquidity edition", 12, ["article", "quiz"]],
  ["options", "options-17", "Assignment, stock delivery and dividend traps", 14, ["article", "caution", "quiz"]],
  ["options", "options-18", "P&L attribution: delta vs vega vs theta", 14, ["article", "quiz"]],
  ["risk", "risk-09", "Gap risk: the stop that does not exist overnight", 14, ["article", "quiz"]],
  ["risk", "risk-10", "Liquidity risk: days-to-exit is a size input", 14, ["article", "formula", "quiz"]],
  ["risk", "risk-11", "Kill switches you are not allowed to negotiate", 14, ["article", "quiz"]],
  ["risk", "risk-12", "VaR is a quantile, not the worst day", 12, ["article", "quiz"]],
  ["desk", "desk-09", "A 12-minute pre-market ritual", 12, ["article", "quiz"]],
  ["desk", "desk-10", "Post-market: force the losers onto the page", 12, ["article", "quiz"]],
  ["desk", "desk-11", "Colour the event calendar, including FOMC nights", 12, ["article", "quiz"]],
  ["desk", "desk-12", "Playbook versioning: one mutation at a time", 12, ["article", "quiz"]],
  ["strategies", "strategies-13", "Flatten is an adjustment; denial is not", 12, ["article", "quiz"]],
  ["strategies", "strategies-14", "Match expiry to the horizon of the view", 12, ["article", "quiz"]],
  ["strategies", "strategies-15", "Ratio spreads: the leftover lot is the trade", 12, ["article", "caution", "quiz"]],
  ["strategies", "strategies-16", "A family-picker table for excited brains", 14, ["article", "table", "quiz"]],
  ["futures", "futures-09", "Futures calendars trade the roll", 12, ["article", "quiz"]],
  ["futures", "futures-10", "SPAN buffers so the broker doesn't trade you", 12, ["article", "quiz"]],
  ["futures", "futures-11", "Stock futures, basis and the ban list", 12, ["article", "quiz"]],
  ["futures", "futures-12", "Extreme-day protocol: margin first", 12, ["article", "quiz"]],
  ["psychology", "psychology-09", "Tilt is a body state — rehearse the protocol", 12, ["article", "quiz"]],
  ["psychology", "psychology-10", "Identity: process, not 'I am an option seller'", 12, ["article", "quiz"]],
  ["psychology", "psychology-11", "After a blow-up: process, then confidence, then capital", 14, ["article", "quiz"]],
  ["psychology", "psychology-12", "Boredom as a professional signal", 12, ["article", "quiz"]],
  ["indices", "indices-01", "Nifty is a recipe, not a mood", 16, ["article", "diagram", "quiz"]],
  ["indices", "indices-02", "Free-float, capping and who you actually own", 14, ["article", "quiz"]],
  ["indices", "indices-03", "Reviews, inclusions and the rebalance calendar", 16, ["article", "quiz"]],
  ["indices", "indices-04", "Bank Nifty is a different animal", 16, ["article", "table", "quiz"]],
  ["indices", "indices-05", "Midcap, Next50 and the liquidity tax", 14, ["article", "formula", "quiz"]],
  ["indices", "indices-06", "India VIX: a thermometer, not a forecast", 16, ["article", "diagram", "quiz"]],
  ["indices", "indices-07", "Breadth: who is actually participating", 14, ["article", "table", "quiz"]],
  ["indices", "indices-08", "Equal-weight versus cap-weight", 14, ["article", "quiz"]],
  ["indices", "indices-09", "Sector indices as a second camera", 14, ["article", "quiz"]],
  ["indices", "indices-10", "An 8-minute index open card", 14, ["article", "worksheet", "quiz"]],
  ["intraday", "intraday-01", "A day trade is a job with a clock", 14, ["article", "table", "quiz"]],
  ["intraday", "intraday-02", "Opening range: break, fail, or skip", 16, ["article", "diagram", "quiz"]],
  ["intraday", "intraday-03", "VWAP as a participation rule", 14, ["article", "table", "quiz"]],
  ["intraday", "intraday-04", "Gap-and-go versus gap-fill", 14, ["article", "formula", "quiz"]],
  ["intraday", "intraday-05", "The 9:20–9:50 protocol", 14, ["article", "quiz"]],
  ["intraday", "intraday-06", "Lunch chop is a product you can refuse", 12, ["article", "quiz"]],
  ["intraday", "intraday-07", "14:30–15:20 is inventory, not discovery", 14, ["article", "quiz"]],
  ["intraday", "intraday-08", "Expiry Thursday as a named session", 16, ["article", "quiz"]],
  ["intraday", "intraday-09", "News spike: a clock, not a hero", 14, ["article", "quiz"]],
  ["intraday", "intraday-10", "Day-trader kill switch", 14, ["article", "worksheet", "quiz"]],
  ["relval", "relval-01", "You are trading a residual, not a story", 16, ["article", "formula", "quiz"]],
  ["relval", "relval-02", "Cash-future basis and cash-and-carry", 16, ["article", "diagram", "quiz"]],
  ["relval", "relval-03", "Reverse cash-and-carry and the borrow", 14, ["article", "quiz"]],
  ["relval", "relval-04", "Nifty versus Bank Nifty as a pair", 16, ["article", "quiz"]],
  ["relval", "relval-05", "Two-stock pairs: beta, residual, kill", 16, ["article", "quiz"]],
  ["relval", "relval-06", "Calendar spreads are the roll", 12, ["article", "quiz"]],
  ["relval", "relval-07", "ETF versus futures residual", 14, ["article", "quiz"]],
  ["relval", "relval-08", "Gold–silver and other commodity ratios", 14, ["article", "quiz"]],
  ["relval", "relval-09", "Why retail cannot run classic index arb", 12, ["article", "quiz"]],
  ["relval", "relval-10", "A relative-value fill sheet", 14, ["article", "worksheet", "quiz"]],
  ["rates", "rates-01", "The corridor: SDF, repo, MSF", 16, ["article", "diagram", "quiz"]],
  ["rates", "rates-02", "LAF, VRR, OMO: operations that move curves", 14, ["article", "quiz"]],
  ["rates", "rates-03", "Level, slope, butterfly on the G-sec curve", 16, ["article", "formula", "quiz"]],
  ["rates", "rates-04", "How a 10-year print hits Bank Nifty", 14, ["article", "quiz"]],
  ["rates", "rates-05", "T-bills, SDLs and the credit stack", 14, ["article", "quiz"]],
  ["rates", "rates-06", "Interest-rate futures without folklore", 12, ["article", "quiz"]],
  ["rates", "rates-07", "Credit spreads: when they blow", 14, ["article", "quiz"]],
  ["rates", "rates-08", "Bank NIMs are not the last repo print", 14, ["article", "quiz"]],
  ["rates", "rates-09", "Real rates, inflation and gold", 14, ["article", "quiz"]],
  ["rates", "rates-10", "A four-minute rates dashboard", 14, ["article", "worksheet", "quiz"]],
  ["fx", "fx-01", "USDINR is a policy pair", 16, ["article", "quiz"]],
  ["fx", "fx-02", "Session hours and the US overlap", 12, ["article", "quiz"]],
  ["fx", "fx-03", "Importer versus exporter tickets", 16, ["article", "quiz"]],
  ["fx", "fx-04", "Oil, FII and the rupee's three bosses", 14, ["article", "table", "quiz"]],
  ["fx", "fx-05", "Intervention is a counterparty", 14, ["article", "quiz"]],
  ["fx", "fx-06", "EURINR and JPYINR as residuals", 12, ["article", "quiz"]],
  ["fx", "fx-07", "USDINR options and event vol", 14, ["article", "quiz"]],
  ["fx", "fx-08", "Offshore weather you cannot see", 14, ["article", "quiz"]],
  ["fx", "fx-09", "Carry slogans versus INR reality", 12, ["article", "quiz"]],
  ["fx", "fx-10", "An FX hedge register", 14, ["article", "worksheet", "quiz"]],
  ["forensic", "forensic-01", "Fraud is a process, not a tweet", 16, ["article", "table", "quiz"]],
  ["forensic", "forensic-02", "Cash versus profit: the first camera", 16, ["article", "formula", "quiz"]],
  ["forensic", "forensic-03", "Related parties and family revenue", 14, ["article", "quiz"]],
  ["forensic", "forensic-04", "Auditor resignations and emphasis", 14, ["article", "quiz"]],
  ["forensic", "forensic-05", "Promoter pledge as a fuse", 14, ["article", "quiz"]],
  ["forensic", "forensic-06", "Working-capital games", 14, ["article", "formula", "quiz"]],
  ["forensic", "forensic-07", "SEBI orders as a research input", 14, ["article", "quiz"]],
  ["forensic", "forensic-08", "Governance is a discount rate", 12, ["article", "quiz"]],
  ["forensic", "forensic-09", "Smallcap illiquidity as a fraud enabler", 14, ["article", "quiz"]],
  ["forensic", "forensic-10", "A two-red walk-away checklist", 14, ["article", "worksheet", "quiz"]],
  ["tradertax", "tradertax-01", "Delivery, intraday and F&O are different tax animals", 16, ["article", "table", "quiz"]],
  ["tradertax", "tradertax-02", "Turnover is not notional", 14, ["article", "quiz"]],
  ["tradertax", "tradertax-03", "ITR-3 and the books you actually need", 14, ["article", "quiz"]],
  ["tradertax", "tradertax-04", "Advance tax so March is not a surprise", 12, ["article", "quiz"]],
  ["tradertax", "tradertax-05", "STT, stamp and GST on the contract note", 16, ["article", "quiz"]],
  ["tradertax", "tradertax-06", "Three sheets: don't mix species", 12, ["article", "quiz"]],
  ["tradertax", "tradertax-07", "Loss carry-forward and on-time filing", 12, ["article", "quiz"]],
  ["tradertax", "tradertax-08", "Monthly close: journal versus ledger", 14, ["article", "quiz"]],
  ["tradertax", "tradertax-09", "GST is not STT", 12, ["article", "quiz"]],
  ["tradertax", "tradertax-10", "A March desk with a CA", 14, ["article", "worksheet", "quiz"]],
  ["intermarket", "intermarket-01", "Four screens, one sentence", 16, ["article", "diagram", "quiz"]],
  ["intermarket", "intermarket-02", "The oil–rupee–Nifty triangle", 16, ["article", "table", "quiz"]],
  ["intermarket", "intermarket-03", "Gold: real rates, dollar, jewellery", 14, ["article", "quiz"]],
  ["intermarket", "intermarket-04", "US 10-year as an EM camera", 14, ["article", "quiz"]],
  ["intermarket", "intermarket-05", "China, metals and Indian materials", 12, ["article", "quiz"]],
  ["intermarket", "intermarket-06", "Overnight gap: classify, then click", 14, ["article", "quiz"]],
  ["intermarket", "intermarket-07", "Crash correlation goes to one", 14, ["article", "quiz"]],
  ["intermarket", "intermarket-08", "Budget, election, monsoon as vol events", 14, ["article", "quiz"]],
  ["intermarket", "intermarket-09", "When the intermarket map lies", 12, ["article", "quiz"]],
  ["intermarket", "intermarket-10", "Layout is a strategy", 14, ["article", "worksheet", "quiz"]],
  ["researchcraft", "researchcraft-01", "A thesis is a sentence with a kill", 16, ["article", "quiz"]],
  ["researchcraft", "researchcraft-02", "Evidence hierarchy: filing before Twitter", 14, ["article", "table", "quiz"]],
  ["researchcraft", "researchcraft-03", "The one-page note", 14, ["article", "worksheet", "quiz"]],
  ["researchcraft", "researchcraft-04", "Kill criteria you cannot negotiate", 14, ["article", "quiz"]],
  ["researchcraft", "researchcraft-05", "Reading a sell-side note without becoming it", 14, ["article", "quiz"]],
  ["researchcraft", "researchcraft-06", "Idea pipeline and a WIP limit", 12, ["article", "quiz"]],
  ["researchcraft", "researchcraft-07", "After-action: process versus luck", 14, ["article", "quiz"]],
  ["researchcraft", "researchcraft-08", "Daily, weekly, quarterly cadence", 14, ["article", "table", "quiz"]],
  ["researchcraft", "researchcraft-09", "Ethics: MNPI is a stop, not an edge", 14, ["article", "quiz"]],
  ["researchcraft", "researchcraft-10", "Write for a tired future you", 14, ["article", "quiz"]],
  ["technicals", "technicals-23", "Relative strength versus the index", 14, ["article", "quiz"]],
  ["technicals", "technicals-24", "Failed breakouts as a named trade", 14, ["article", "quiz"]],
  ["technicals", "technicals-25", "Delivery % needs volume context", 14, ["article", "quiz"]],
  ["technicals", "technicals-26", "Higher timeframe is a veto", 14, ["article", "quiz"]],
  ["funds", "funds-15", "SEBI boxes and closet indexing", 14, ["article", "quiz"]],
  ["funds", "funds-16", "Rolling returns beat since-inception ads", 14, ["article", "quiz"]],
  ["funds", "funds-17", "Debt funds: duration and credit dials", 14, ["article", "quiz"]],
  ["funds", "funds-18", "Factor ETFs are recipes with a calendar", 14, ["article", "quiz"]],
  ["sectors", "sectors-09", "PSU banks versus private banks", 14, ["article", "quiz"]],
  ["sectors", "sectors-10", "NBFC ALM is the job", 14, ["article", "quiz"]],
  ["sectors", "sectors-11", "Insurance: EV and combined ratio, not a poster", 14, ["article", "quiz"]],
  ["sectors", "sectors-12", "Realty: inventory and collections", 14, ["article", "quiz"]],
  ["sectors", "sectors-13", "Capital goods: order book versus cash", 14, ["article", "quiz"]],
  ["sectors", "sectors-14", "Chemicals: name the spread", 14, ["article", "quiz"]],
  ["regulations", "regulations-09", "PIT, UPSI and why a cousin is not an edge", 14, ["article", "quiz"]],
  ["regulations", "regulations-10", "Peak margin and VAR+ELM", 14, ["article", "quiz"]],
  ["regulations", "regulations-11", "Broker default, idle cash and IPEF", 12, ["article", "quiz"]],
  ["regulations", "regulations-12", "Nomination and a yearly account map", 12, ["article", "quiz"]],
  ["commodities", "commodities-15", "MCX options: liquidity is the product", 14, ["article", "quiz"]],
  ["commodities", "commodities-16", "COMEX–MCX is a residual, not a phone arb", 14, ["article", "quiz"]],
  ["commodities", "commodities-17", "Agri seasonality is a prior, not a ticket", 12, ["article", "quiz"]],
  ["commodities", "commodities-18", "Energy cracks: don't double oil-beta", 14, ["article", "quiz"]],
  ["ai", "ai-07", "RAG on filings: cite the paragraph", 14, ["article", "quiz"]],
  ["ai", "ai-08", "Prompt hygiene: force the card", 12, ["article", "quiz"]],
  ["ai", "ai-09", "Evaluate the copilot like a junior", 12, ["article", "quiz"]],
  ["ai", "ai-10", "When not to use AI (including MNPI)", 12, ["article", "quiz"]],
  ["modelling", "modelling-09", "Don't FCF a bank", 14, ["article", "quiz"]],
  ["modelling", "modelling-10", "Residual income and cheap P/B traps", 14, ["article", "formula", "quiz"]],
  ["modelling", "modelling-11", "No silent plugs", 12, ["article", "quiz"]],
  ["modelling", "modelling-12", "Compress the model to a sentence", 12, ["article", "quiz"]],
  ["bonds", "bonds-09", "Curve butterflies are curvature, not 'I like bonds'", 12, ["article", "quiz"]],
  ["bonds", "bonds-10", "T-bill auctions as a short-end camera", 12, ["article", "quiz"]],
  ["bonds", "bonds-11", "Floaters and inflation paper are not fixed gilts", 12, ["article", "quiz"]],
  ["bonds", "bonds-12", "Credit-spread duration", 14, ["article", "formula", "quiz"]],
  ["volatility", "volatility-11", "India VIX versus the weekly straddle", 14, ["article", "quiz"]],
  ["volatility", "volatility-12", "Vol-of-vol: the thermometer can jump", 14, ["article", "quiz"]],
  ["volatility", "volatility-13", "Weekend theta is not a gift if Monday jumps", 14, ["article", "quiz"]],
  ["volatility", "volatility-14", "Event-vol crush with a number", 16, ["article", "formula", "quiz"]],
  ["options", "options-19", "Synthetics: accidental futures in costume", 14, ["article", "quiz"]],
  ["options", "options-20", "Boxes vs Indian weekly costs", 12, ["article", "quiz"]],
  ["desk", "desk-13", "A 25-minute weekly review", 12, ["article", "quiz"]],
  ["desk", "desk-14", "Apprenticeship 2.0: depth before width", 12, ["article", "quiz"]],
  ["library", "library-05", "Advanced glossary: words need numbers", 14, ["article", "table", "quiz"]],
];

const PATHS = [
  {
    id: "start",
    title: "Start here",
    blurb: "Zero to literate: how markets work in India.",
    lessons: ["foundations-01", "india-01", "india-02", "equity-01", "equity-02", "risk-01", "psychology-01"],
  },
  {
    id: "investor",
    title: "Investor path",
    blurb: "Own businesses, not tickers.",
    lessons: ["equity-01", "fundamentals-01", "fundamentals-05", "fundamentals-14", "fundamentals-15", "fundamentals-18", "equity-07", "regulations-03", "risk-08"],
  },
  {
    id: "trader",
    title: "Trader path",
    blurb: "Process, risk, psychology, then setups.",
    lessons: ["technicals-01", "technicals-08", "technicals-16", "technicals-22", "psychology-03", "risk-02", "desk-01", "desk-08"],
  },
  {
    id: "derivatives",
    title: "Derivatives path",
    blurb: "Futures, options theory, then strategies.",
    lessons: ["futures-01", "futures-03", "options-01", "options-05", "options-09", "positioning-02", "positioning-08", "positioning-09", "strategies-01", "options-08"],
  },
  {
    id: "oi-greeks",
    title: "OI & Greeks desk",
    blurb: "Open interest, walls, dealer gamma, theta and a daily Nifty checklist.",
    lessons: ["options-05", "options-09", "positioning-01", "positioning-04", "positioning-08", "positioning-09", "positioning-10", "positioning-12"],
  },
  {
    id: "charts",
    title: "Charts & indicators",
    blurb: "From structure to ATR, Supertrend, ADX and a stack that does not fight itself.",
    lessons: ["technicals-01", "technicals-05", "technicals-13", "technicals-14", "technicals-15", "technicals-16", "technicals-18", "technicals-22"],
  },
  {
    id: "ai-desk",
    title: "AI on the desk",
    blurb: "Make research faster without handing the order button to a model.",
    lessons: ["ai-01", "ai-02", "ai-04", "ai-05", "ai-06"],
  },
  {
    id: "wealth",
    title: "Long-term wealth path",
    blurb: "Funds, bonds, insurance and NPS for a household book.",
    lessons: ["funds-01", "funds-04", "funds-11", "funds-12", "funds-10", "bonds-01", "insurance-01", "nps-01"],
  },
  {
    id: "commodities-desk",
    title: "Commodities path",
    blurb: "Gold, silver, energy, BeES vs futures, then a written strategy card.",
    lessons: ["commodities-01", "commodities-02", "commodities-09", "commodities-11", "commodities-13", "commodities-14", "funds-14"],
  },
  {
    id: "vol-desk",
    title: "Volatility desk path",
    blurb: "IV vs RV, skew, selling jumps, calendars, then a shock cell.",
    lessons: ["options-04", "options-05", "volatility-01", "volatility-02", "volatility-03", "volatility-05", "volatility-09", "options-18"],
  },
  {
    id: "specials-path",
    title: "Special situations path",
    blurb: "Document plus date: earnings, buybacks, demergers, leftover plan.",
    lessons: ["specials-01", "specials-02", "specials-03", "specials-04", "specials-05", "specials-10"],
  },
  {
    id: "macro-path",
    title: "Macro path",
    blurb: "RBI, rupee, crude, FII, Budget, a six-cell overnight note.",
    lessons: ["macro-01", "macro-02", "macro-03", "macro-05", "macro-06", "macro-10"],
  },
  {
    id: "pro-desk",
    title: "Advanced desk path",
    blurb: "Microstructure, hedges, systems, kill switch, 12-minute open.",
    lessons: ["microstructure-01", "microstructure-04", "hedging-01", "hedging-03", "systems-01", "systems-02", "risk-11", "desk-09"],
  },
  {
    id: "day-path",
    title: "Intraday path",
    blurb: "Opening range, VWAP, expiry Thursday, a kill switch.",
    lessons: ["intraday-01", "intraday-02", "intraday-03", "intraday-05", "intraday-08", "intraday-10"],
  },
  {
    id: "rates-path",
    title: "Rates & FX path",
    blurb: "Corridor, curve, USDINR bosses, then a dashboard.",
    lessons: ["rates-01", "rates-03", "rates-04", "fx-01", "fx-04", "rates-10"],
  },
  {
    id: "forensic-path",
    title: "Forensic path",
    blurb: "Cash vs profit, pledge, SEBI orders, two-red walk-away.",
    lessons: ["forensic-01", "forensic-02", "forensic-05", "forensic-07", "forensic-10", "researchcraft-01"],
  },
  {
    id: "relval-path",
    title: "Relative-value path",
    blurb: "Basis, BN vs Nifty, leftover beta, a fill sheet.",
    lessons: ["relval-01", "relval-02", "relval-04", "relval-07", "relval-10", "indices-06"],
  },
  {
    id: "tax-ops",
    title: "Tax & operations path",
    blurb: "F&O as business income, STT 0.15%, peak margin, March desk.",
    lessons: ["tradertax-01", "tradertax-02", "tradertax-05", "tradertax-10", "regulations-10", "regulations-02"],
  },
];

function lessonMeta() {
  return LESSONS.map(([trackId, id, title, minutes, formats], index) => ({
    id,
    trackId,
    title,
    minutes,
    formats,
    index,
    number: LESSONS.filter((row) => row[0] === trackId).findIndex((row) => row[1] === id) + 1,
  }));
}

const LESSON_LIST = lessonMeta();
const LESSON_BY_ID = Object.fromEntries(LESSON_LIST.map((l) => [l.id, l]));
const TRACK_BY_ID = Object.fromEntries(TRACKS.map((t) => [t.id, t]));

function lessonsForTrack(trackId) {
  return LESSON_LIST.filter((l) => l.trackId === trackId);
}

function getLesson(id) {
  return LESSON_BY_ID[id] || null;
}

function getTrack(id) {
  return TRACK_BY_ID[id] || null;
}

function neighbors(id) {
  const i = LESSON_LIST.findIndex((l) => l.id === id);
  return {
    prev: i > 0 ? LESSON_LIST[i - 1] : null,
    next: i >= 0 && i < LESSON_LIST.length - 1 ? LESSON_LIST[i + 1] : null,
  };
}

function searchLessons(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return LESSON_LIST;
  return LESSON_LIST.filter((l) => {
    const track = TRACK_BY_ID[l.trackId];
    return (
      l.title.toLowerCase().includes(q) ||
      l.id.includes(q) ||
      track?.title.toLowerCase().includes(q) ||
      l.formats.join(" ").includes(q)
    );
  });
}

module.exports = {
  TRACKS,
  PATHS,
  LESSON_LIST,
  lessonsForTrack,
  getLesson,
  getTrack,
  neighbors,
  searchLessons,
};
